apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: tc-pipeline-run-
spec:
  pipelineRef:
    name: tc-pipeline
  workspaces:
    - name: pipeline-workspace
      persistentVolumeClaim:
        claimName: pipelinerun-pvc
    - name: dockerconfig-ws
      secret:
        secretName: docker-reg-creds
  params:
    - name: repo-url
      value: https://github.com/kamaladams2025/zntwk-tax_calculator.git
    - name: branch
      value: main
    - name: app-name
      value: tax-calculator